GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/api/blogs/9
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlkIjoyLCJpYXQiOjE2NDcwMjA1MTJ9.jV-l8gh_atzEUIwR8xfGUYKbiHFEkr99w5DlO5XcYbI

{
  "author": "authorx",
  "url": "urlx",
  "title": "titlex",
  "likes": 10
}
###
DELETE http://localhost:3001/api/blogs/20
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlkIjoyLCJpYXQiOjE2NDcwNDQ3NzZ9.gW4lFvjJ1Fd-wj-Pls3qWuqw9wyja2Z3OkCf0cavKcg
###
PUT http://localhost:3001/api/blogs/100
Content-Type: application/json

{
  "likes": 3
}
