GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/api/blogs/9
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMUBtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2NDcxMTgwOTF9.n8IDjeLIrVj5pZW6rgvR17lGmZ8ln7QtRsCDUfX3_Wo

{
  "author": "authorz",
  "url": "urlz",
  "title": "titlez",
  "likes": 10,
  "year":2022
}
###
DELETE http://localhost:3001/api/blogs/20
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlkIjoyLCJpYXQiOjE2NDcwNDQ3NzZ9.gW4lFvjJ1Fd-wj-Pls3qWuqw9wyja2Z3OkCf0cavKcg
###
PUT http://localhost:3001/api/blogs/100
Content-Type: application/json

{
  "likes": 3
}
